- hosts: localhost
  become: yes
  tasks:
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: "https://github.com/Malikjanmulla/final-devops-project.git"
        name: docker.io/malikjanmulla/abctechnology
        push: true
        source: build
      register: out
    - debug:
        var: out
