- hosts: localhost
  become: yes
  tasks:
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: "/etc/ansible/"
        name: docker.io/malikjanmulla/abctechnology
        push: true
        source: build
      register: out
    - debug:
        var: out
